name: Update Mobile Alerts

# Run every day at midnight UTC (adjust as needed)
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # allows manual run

jobs:
  update_alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish KV data
        run: |
          wrangler kv:key put \
            --namespace-id ${{ secrets.KV_NAMESPACE_ID }} \
            --key "osm-data" \
            --value "$(cat mobile_alerts.json)"
